bekindred/bekindred/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from tastypie.api import Api

from accounts.api.resources import (
    LinkedinSocialConnectResource,
    LinkedinSocialDisconnectResource,
    SocialLoginResource,
    TwitterSocialConnectResource,
    TwitterSocialDisconnectResource
)
from events.api.resources import (
    AboutMeResource,
    Attendees,
    EventAttendees,
    EventConnections,
    EventFeedResource,
    EventResource,
    FilterStateResource,
    MembershipResource,
    OrganizerResource,
    UserProfileResource,
    SharedInterestsResource
)
from friends.api.resources import (
    ConnectionsResource,
    ConnectionsSearchResource,
    FriendsNewCounterResource,
    FriendsNewResource,
    FriendsResource,
    MutualFriendsCountResource,
    NeoFriendsNewCounterResource,
    NeoFriendsNewResource,
    NeoFriendsResource
)
from goals.api.resources import (
    FacebookLikeResource,
    FacebookMutualLikeResource,
    FacebookOtherLikeResource,
    GoalResource,
    MatchFilterStateResource,
    OfferResource,
    SubjectResource
)
from interests.api.resources import (
    InterestResource,
    InterestSubjectResource,
    PoliticalIndexResource,
    PoliticalViewResource,
    ReligiousIndexResource,
    ReligiousViewResource
)
from matchfeed.api.resources import (
    MatchedFeedResource,
    MutualConnections,
    MutualFriendsResource,
    ProfileResource
)
from msgs.api.resources import (
    ChatMessageResource,
    InboxLastResource,
    InboxResource,
    MessageResource,
    UnreadMessageCounter
)
from photos.api.resources import (
    FacebookPhotoResource,
    OnBoardingFlowResource,
    UserResource
)
from world.api.resources import UserLocationResource

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(SubjectResource())
v1_api.register(UserResource())
v1_api.register(AboutMeResource())
v1_api.register(MatchFilterStateResource())
v1_api.register(FacebookPhotoResource())
v1_api.register(GoalResource())
v1_api.register(OfferResource())
v1_api.register(MatchedFeedResource())
v1_api.register(MutualFriendsResource())
v1_api.register(ProfileResource())
v1_api.register(MessageResource())
v1_api.register(InterestResource())
v1_api.register(InterestSubjectResource())
v1_api.register(FriendsResource())
v1_api.register(ConnectionsSearchResource())
v1_api.register(ConnectionsResource())
v1_api.register(FacebookLikeResource())
v1_api.register(FacebookMutualLikeResource())
v1_api.register(FacebookOtherLikeResource())
v1_api.register(InboxResource())
v1_api.register(InboxLastResource())
v1_api.register(UnreadMessageCounter())
v1_api.register(UserLocationResource())
v1_api.register(FriendsNewResource())
v1_api.register(FriendsNewCounterResource())
v1_api.register(EventResource())
v1_api.register(MembershipResource())
v1_api.register(FilterStateResource())
v1_api.register(EventFeedResource())
v1_api.register(EventConnections())
v1_api.register(EventAttendees())
v1_api.register(ChatMessageResource())
v1_api.register(OnBoardingFlowResource())
v1_api.register(ReligiousViewResource())
v1_api.register(ReligiousIndexResource())
v1_api.register(PoliticalViewResource())
v1_api.register(PoliticalIndexResource())
v1_api.register(UserProfileResource())

v2_api = Api(api_name='v2')
v2_api.register(NeoFriendsResource())
v2_api.register(NeoFriendsNewCounterResource())
v2_api.register(NeoFriendsNewResource())
v2_api.register(Attendees())
v2_api.register(MutualConnections())
v2_api.register(MutualFriendsCountResource())
v2_api.register(SocialLoginResource())
v2_api.register(TwitterSocialConnectResource())
v2_api.register(TwitterSocialDisconnectResource())
v2_api.register(LinkedinSocialConnectResource())
v2_api.register(LinkedinSocialDisconnectResource())
v2_api.register(OrganizerResource())
v2_api.register(SharedInterestsResource())


urlpatterns = patterns('',
                       url(r'^signup/interests', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/goals', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/offers', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/connect', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/$', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^api/', include(v1_api.urls)),
                       url(r'^api/', include(v2_api.urls)),
                       url(r'^facebook/', include('django_facebook.urls')),
                       url(r'^social/', include('social_auth.urls')),
                       url(r'^goals/close_login_popup/$', 'goals.views.close_login_popup', name='close_login_popup'),
                       url(r'^goals/error_window/$', 'goals.views.error_window', name='error_window'),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
                       url(r'^login/$', 'django.contrib.auth.views.login',
                           {'template_name': 'registration/login_dev.html'}, name='auth_login_dev'),
                       url(r'^accounts/', include('django_facebook.auth_urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       )


urlpatterns += patterns('',
                        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.MEDIA_ROOT}))

urlpatterns += patterns('',
                        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.STATIC_ROOT}))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            url(r'api/doc/', include('tastypie_swagger.urls', namespace='tastypie_swagger'))
                            )


urlpatterns += patterns('',
                        url(r'^.*$', 'goals.views.main_app')
                        )

bekindred/photos/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from .views import PhotoListView, PhotoDeleteView, CreateFacebookPhoto, photo_list

urlpatterns = patterns('',
                       url(r'^main/$', TemplateView.as_view(template_name="photos/main_photos.html")),
                       url(r'^create/$', photo_list, name='photo_list'),
                       url(r'^list/$', PhotoListView.as_view(), name='photo_create'),
                       url(r'^delete/(?P<pk>\d+)$', PhotoDeleteView.as_view(), name='photo_delete'),
                       url(r'^facebook/create$', CreateFacebookPhoto.as_view()),
                       )

bekindred/goals/models.py
from django.db import models
from django_facebook.models import FacebookCustomUser
from djorm_pgfulltext.models import SearchManager
from djorm_pgfulltext.fields import VectorField


class SubjectManager(models.Manager):
    def search_goals(self, user_id):
        user_goals = Goal.objects.filter(user=FacebookCustomUser.objects.get(pk=user_id))

        subjects = Subject.objects.exclude(id__in=user_goals.values_list('id', flat=True))
        search_subject = []
        for goal in user_goals:
            # FTS extension by default uses plainto_tsquery instead of to_tosquery,
            #  for this reason the use of raw parameter.
            tsquery = ' | '.join(unicode(goal).split())
            search_subject.extend(subjects.search(tsquery, raw=True))

        return search_subject

    def search_offers(self, user_id):
        user_offers = Offer.objects.filter(user=FacebookCustomUser.objects.get(pk=user_id))

        subjects = Subject.objects.exclude(id__in=user_offers.values_list('id', flat=True))
        search_subject = []
        for offer in user_offers:
            # FTS extension by default uses plainto_tsquery instead of to_tosquery,
            #  for this reason the use of raw parameter.
            tsquery = ' | '.join(unicode(offer).split())
            search_subject.extend(subjects.search(tsquery, raw=True))

        return search_subject


class Subject(models.Model):
    description = models.CharField(max_length=300, null=False, blank=False, unique=True)

    search_index = VectorField()

    objects = SearchManager(
        fields=('description', ),
        config='pg_catalog.english',
        search_field='search_index',
        auto_update_search_field=True
    )
    search_subject = SubjectManager()

    def __unicode__(self):
        return self.description


class GoalManager(models.Manager):
    def user_goals(self, user_id):
        return Goal.objects.filter(user=FacebookCustomUser.objects.get(pk=user_id)).values('goal')

    def match_offers_to_goals(self, exclude_friends, user_offers):
        return list(Goal.objects.exclude(user__in=exclude_friends).filter(goal=user_offers).values_list('user', flat=True))

    def match_goals_to_goals(self, exclude_friends, user_goals):
        return list(Goal.objects.exclude(user__in=exclude_friends).filter(goal=user_goals).values_list('user', flat=True))

    def search_offers_to_goals(self, exclude_friends, search_goals):
        return list(Goal.objects.exclude(user_id__in=exclude_friends).
                    filter(goal__in=search_goals).values_list('user', flat=True))

    def search_goals_to_goals(self, exclude_friends, search_goals):
        return list(Goal.objects.exclude(user_id__in=exclude_friends).
                    filter(goal__in=search_goals).values_list('user', flat=True))


class Goal(models.Model):
    objects = GoalManager()
    user = models.ForeignKey(FacebookCustomUser)
    goal = models.ForeignKey(Subject)

    def __unicode__(self):
        return self.goal.description

    class Meta:
        unique_together = ("user", "goal")


class OfferManager(models.Manager):
    def user_offers(self, user_id):
        return Offer.objects.filter(user=FacebookCustomUser.objects.get(pk=user_id)).values('offer')

    def match_goals_to_offers(self, exclude_friends, user_goals):
        return list(Offer.objects.exclude(user__in=exclude_friends).
                    filter(offer=user_goals).values_list('user', flat=True))

    def match_offers_to_offers(self, exclude_friends, user_offers):
        return list(Offer.objects.exclude(user__in=exclude_friends).
                    filter(offer=user_offers).values_list('user', flat=True))

    def search_goals_to_offers(self, exclude_friends, search_goals):
        return list(Offer.objects.exclude(user_id__in=exclude_friends).
                    filter(offer__in=search_goals).values_list('user', flat=True))

    def search_offers_to_offers(self, exclude_friends, search_offers):
        return list(Offer.objects.exclude(user_id__in=exclude_friends).
                    filter(offer__in=search_offers).values_list('user', flat=True))


class Offer(models.Model):
    objects = OfferManager()
    user = models.ForeignKey(FacebookCustomUser)
    offer = models.ForeignKey(Subject)

    def __unicode__(self):
        return self.offer.description

    class Meta:
        unique_together = ("user", "offer")


class KeywordManager(models.Manager):
    def goal_keywords(self, user_id):
        from django.db import connection
        cursor = connection.cursor()
        cursor.execute("SELECT "
                       "strip(to_tsvector(s.description)) as keywords "
                       "FROM goals_subject s, goals_goal g "
                       "WHERE g.goal_id = s.id "
                       "AND g.user_id = %s", [user_id])
        result_list = []
        for row in cursor.fetchall():
            result_list.append(','.join(row[0].split()))
        return result_list

    def offer_keywords(self, user_id):
        from django.db import connection
        cursor = connection.cursor()
        cursor.execute("SELECT "
                       "strip(to_tsvector(s.description)) as keywords "
                       "FROM goals_subject s, goals_offer g "
                       "WHERE g.offer_id = s.id "
                       "AND g.user_id = %s", [user_id])
        result_list = []
        for row in cursor.fetchall():
            result_list.append(','.join(row[0].split()))
        return result_list


class Keyword(models.Model):
    text = models.CharField(max_length=20)
    subject = models.ForeignKey(Subject)
    objects = KeywordManager()


class UserIPAddress(models.Model):
    user = models.OneToOneField(FacebookCustomUser)
    ip = models.IPAddressField()


class MatchFilterState(models.Model):
    user = models.ForeignKey(FacebookCustomUser)
    distance = models.IntegerField(default=10000)
    distance_unit = models.CharField(max_length=5, default='miles')
    min_age = models.CharField(max_length=3, default=25)
    max_age = models.CharField(max_length=4, default=60)
    gender = models.CharField(max_length=3, default='m,f')
    keyword = models.CharField(max_length=50, default='')
    order_criteria = models.CharField(max_length=20, default='match_score')

bekindred/goals/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from open_facebook import OpenFacebook

from .forms import BiographyForm
from goals.utils import social_extra_data
from members.models import FacebookCustomUserActive
from .models import UserIPAddress
import logging

logger = logging.getLogger(__name__)


def register(request):
    """
    Mock for django_facebook register
    """
    return HttpResponseRedirect(reverse('auth_login'))


def biography_update(request, pk, template_name='goals/biography_form.html'):
    user = FacebookCustomUserActive.objects.get(pk=pk)
    form = BiographyForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/goals')
    return render(request, template_name, {'form': form})


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


@login_required
def profile_view(request, username):
    fb = FacebookCustomUserActive.objects.get(username=username)
    context = RequestContext(request, {
        'first_name': fb.first_name,
        'last_name': fb.last_name,
    })
    return render_to_response('goals/user_profile.html', context)


@login_required
def main_app(request, template_name="homepage_mainapp.html"):
    # if not request.user.is_staff and request.flavour == u'full':
    #     logout(request)
    #     return render_to_response("registration/login.html", {'hide': True})
    twitter_provider, linkedin_provider, twitter_username, linkedin_first_name = social_extra_data(request.user.id)
    context = RequestContext(request, {
        'twitter_provider': twitter_provider,
        'linkedin_provider': linkedin_provider,
        'linkedin_first_name': linkedin_first_name,
        'twitter_username': twitter_username,
    })

    if request.user.is_authenticated():
        fb_user = FacebookCustomUserActive.objects.get(pk=request.user.id)
        try:
            UserIPAddress.objects.get(user=request.user.id)
        except UserIPAddress.DoesNotExist:
            user = UserIPAddress.objects.create(user=fb_user, ip=get_client_ip(request))
            user.save()

    if not hasattr(request.user, 'onboardingflow'):
        return redirect('onboardingflow')
    elif hasattr(request.user, 'onboardingflow') and not \
            request.user.onboardingflow.is_complete:
        return redirect('onboardingflow')
        # if fb_user.facebook_id and fb_user.access_token \
        #         and not fb_user.about_me:
        #     facebook = OpenFacebook(fb_user.access_token)
        #     fb_user.about_me = facebook.get('me').get('bio', None)
        #     fb_user.save()
    logger.info('User open main page', exc_info=True, extra={
        'request': request})
    return render_to_response(template_name, context)


@login_required
def signup_page(request, template_name="homepage_signup.html"):
    twitter_provider, linkedin_provider, twitter_username, linkedin_first_name \
        = social_extra_data(request.user.id)
    context = RequestContext(request, {
        'twitter_provider': twitter_provider,
        'linkedin_provider': linkedin_provider,
        'twitter_username': twitter_username,
        'linkedin_first_name': linkedin_first_name,
    })

    if request.user.is_authenticated():
        fb_user = FacebookCustomUserActive.objects.get(pk=request.user.id)
        try:
            UserIPAddress.objects.get(user=request.user.id)
        except UserIPAddress.DoesNotExist:
            user = UserIPAddress.objects.create(user=fb_user, ip=get_client_ip(request))
            user.save()

        # if fb_user.facebook_id and fb_user.access_token \
        #         and not fb_user.about_me:
        #     facebook = OpenFacebook(fb_user.access_token)
        #     fb_user.about_me = facebook.get('me').get('bio', None)
        #     fb_user.save()
    return render_to_response(template_name, context)


def close_login_popup(request):
    return render_to_response('goals/close_popup.html', {}, RequestContext(request))


def error_window(request):
    return render_to_response('error_window.html', {}, RequestContext(request))

bekindred/templates/goals/close_popup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>

 <script type="text/javascript">

    function closeAndUpdate()
    {
        if (window.opener) {
            window.opener.refreshConnect();
            window.close();
        }
    }

    closeAndUpdate();



</script>
</body>
</html>

bekindred/templates/goals/create_goal.html
{% extends 'base.html' %}

{% block content %}

<div class="body segment">
<div class="container">
        {% include 'goals/subject_form.html' with button_name="Add goal" %}
    </div>
</div>
{% endblock content %}

bekindred/templates/goals/create_offer.html
{% extends 'base.html' %}

{% block content %}

<div class="body segment">
    <div class="container">
        {% include 'goals/subject_form.html' with button_name="Add offer" %}
    </div>
</div>
{% endblock content %}

bekindred/templates/goals/goal.html
{% extends 'base.html' %}
{% block content %}
<div class="headersmall segment">
    <div class="container">
        <h3 class="ui center aligned header">
            <span class="fa-stack">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-stack-1x fa-inverse">1</i>
            </span>
            Create Goal
        </h3>
    </div>
</div>
<div class="body segment">
    <div class="container">
        <h2 class="ui center aligned header">My goal is to...</h2>
        {% include 'goals/subject_form.html' with button_name="Next &rarr;" %}
        <div class="ui secondary segment">
            <h3>Here are some examples</h3>
            <p>
                {% include 'goals/examples_list.html' %}
            </p>
        </div>
    </div>
</div>
{% endblock content %}

bekindred/templates/goals/goal_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<section class="subtitle-wrapper">
    <div class="row">
        <div class="medium-10 small-centered columns">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
            </span>
            <h5>Delete Goal?</h5>
        </div>
    </div>
</section>
<section class="edit-wrapper">
    <div class="row">
        <div class="columns small-centered small-12 medium-6 large-4">
            <form class="" action="" method="post">{% csrf_token %}
                <div data-alert class="alert-box alert">
                    Are you sure you want to delete <strong>"{{ object.description }}"</strong>?
                    <a href="" class="close">×</a>
                </div>
                <br>
                <a class="button delete success radius" href="/goals">Cancel</a>
                <button type="submit" class="danger submit-button radius">Delete</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

bekindred/templates/goals/goal_form.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-muted text-center">
    My goal is to...
</h1>
<br>
<div class="container col-md-12 col-md-offset-5">
    <form class="form-horizontal" role="form" action="" method="post">{% csrf_token %}
        <div class="text-center col-sm-2">
            <input type="text" name="description" class="form-control" id="id_description" placeholder="enter you goal here">
        </div>
        <input type="submit" class="btn btn-primary" role="button" value="Create" />
    </form>
</div>
<div class="container col-md-12 col-md-offset-5">
    <br>
    <p>Here are some examples:</p>
    <ul>
        <li>"Learn to play tennis"</li>
        <li>"Find a running partner"</li>
        <li>"Hire a cat sitter"</li>
        <li>"Move my 500 lb sofa"</li>
    </ul>
</div>
{% endblock content %}

bekindred/templates/goals/my_page.html
{% extends 'base.html' %}

{% block content %}
<div ng-controller="MyPageController">
    <div class="header segment with-menu" id="my-profile-header">
        <div class="container">
            {% verbatim %}
            <div class="pagination-container">

                <div class="swiper-container">
                    <div class="swiper-wrapper" ng-cloak>

                    <div class="swiper-slide" ng-repeat="photo in photosSlider | orderBy:'order' track by $index" end-repeat>
                            <div class="ui medium image img-bounding-box-fix-size" style="background-image: url('{{photo.photo}}')"></div>
                        </div>

                    </div>
                </div>


                <div class="pagination" ng-show="photosSlider.length > 1"></div>
            </div>
            {% endverbatim %}
        </div>
    </div>

    <div class="body segment" id="my-profile-body">
        <div class="container">
            <div class="ui attached segment" id="my-profile-title">
                <h3 class="ui left floated header">
                    {{ user.first_name|capfirst }}, {{age}}
                </h3>
                <h3 class="ui right floated header">
                    <a href="/goals/edit/user" class="ui tiny button blue">Edit</a>
                </h3>
            </div>
            <div class="ui attached segment">
                <h4 class="ui header">Goals</h4>
                <div class="profile-icon">
                    <div class="ui mini statistic">
                        <div class="value">
                            <i class="unordered list large icon"></i>
                        </div>
                        <div class="label">
                            2
                        </div>
                    </div>
                </div>
                <div class="ui list">
                    {% for goal in goals %}
                    <div class="item">
                        <div class="content">
                            <div class="description">{{ goal }}</div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="item">
                        <div class="content">
                            <div class="description">No goals yet.</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>


                <h4 class="ui header">Offers</h4>
                <div class="ui list">
                    {% for offer in offers %}
                    <div class="item">
                        <div class="content">
                            <div class="description">{{ offer }}</div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="item">
                        <div class="content">
                            <div class="description">No offers yet.</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <h4 class="ui header">About</h4>
                <div class="ui list">
                    <div class="item">
                        <div class="content">
                            <div class="description">
                                {% if user_obj.profile_or_self.about_me  %}
                                {{ user.profile_or_self.about_me }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <h4 class="ui header">Likes</h4>
                <div class="ui list">
                    {% for like in user.profile_or_self.likes|slice:":5" %}
                    <div class="item">
                        <div class="content">
                            <div class="description">{{ like.name }}</div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="item">
                        <div class="content">
                            <div class="description">No likes yet.</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>

        </div>
    </div>


</div>

{% endblock content %}

{% block customscripts %}

<script>




</script>

{% endblock customscripts %}

bekindred/templates/goals/no_match_results.html
{% extends 'base.html' %}
{% block content %}
<div class="body segment">
    <div class="container">
        <div class="ui info message">
            <div class="header">
                Sorry
            </div>
            <p>No match results.</p>
        </div>

    </div>
</div>
{% endblock content %}

bekindred/templates/goals/offer_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<section class="subtitle-wrapper">
    <div class="row">
        <div class="medium-10 small-centered columns">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
            </span>
            <h5>Delete Offer?</h5>
        </div>
    </div>
</section>
<section class="edit-wrapper">
    <div class="row">
        <div class="columns small-centered small-12 medium-6 large-4">
            <form class="" action="" method="post">{% csrf_token %}
                <div data-alert class="alert-box alert">
                    Are you sure you want to delete <strong>"{{ object.description }}"</strong>?
                    <a href="" class="close">×</a>
                </div>
                <br>
                <a class="button delete success radius" href="/goals">Cancel</a>
                <button type="submit" class="danger submit-button radius">Delete</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

bekindred/templates/goals/subject_form.html
{% for k, message in form.errors.items %}
<div class="ui negative message">
    <div class="header">
        {{message|striptags}}
    </div>
</div>
{% endfor %}
<div class="ui form">
    <form class="form" role="form" action="" method="post" novalidate>
        {% csrf_token %}
        <div class="ui center aligned grid">
            <div class="row">
                <div class="column">
                    <div class="search-wrapper ui icon large left input" ng-controller="GoalsController">
                        <i class="fa fa-search fa-lg"></i>
                        <div field-required="true" angucomplete-alt minlength="3" match-class="highlight" selected-object="goalSelected" description-field="description[3]" title-field="description" remote-url="/api/v1/subject/?format=json&description__contains=" remote-url-data-field="objects" type="text" input-name="description" id="id_description" placeholder="enter your {% if '/goals/create/goal/' == request.path %}goal{%endif%}{% if '/goals/create/offer/' == request.path %}offer{%endif%} here"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="column">
                    <button type="submit" class="ui button submit green big" role="button">Next &rarr;</button>
                </div>
            </div>
        </div>
    </form>
</div>

bekindred/templates/goals/update_goal.html
{% extends 'base.html' %}

{% block content %}
<div class="body segment">
    <div class="container">

        <div class="ui error form segment">

         {% if form.errors %}
         {% for field in form %}
         {% for error in field.errors %}
         <div class="ui error message">
            <div class="header"><strong>{{ field.label }}:</strong> {{ error|escape }}</div>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}
        <form class="" action="" method="post">{% csrf_token %}


            <div class="field">
                <label>New description: </label>
                {{ form.description }}
            </div>



            <button type="submit" class="ui submit green button">Save</button>
        </form>

    </div>

</div>
</div>

{% endblock content %}

bekindred/templates/goals/update_offer.html
{% extends 'base.html' %}

{% block content %}
<div class="body segment">
    <div class="container">

        <div class="ui error form segment">

           {% if form.errors %}
           {% for field in form %}
           {% for error in field.errors %}
           <div class="ui error message">
            <div class="header"><strong>{{ field.label }}:</strong> {{ error|escape }}</div>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}
        <form class="" action="" method="post">{% csrf_token %}


            <div class="field">
            <label>New description: </label>
                {{ form.description }}
            </div>



            <button type="submit" class="ui submit green button">Save</button>
        </form>

    </div>

</div>
</div>

{% endblock content %}

bekindred/templates/goals/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ first_name }} {{ last_name }}</h1>
</body>
</html>