bekindred/bekindred/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from tastypie.api import Api

from accounts.api.resources import (
    LinkedinSocialConnectResource,
    LinkedinSocialDisconnectResource,
    SocialLoginResource,
    TwitterSocialConnectResource,
    TwitterSocialDisconnectResource
)
from events.api.resources import (
    AboutMeResource,
    Attendees,
    EventAttendees,
    EventConnections,
    EventFeedResource,
    EventResource,
    FilterStateResource,
    MembershipResource,
    OrganizerResource,
    UserProfileResource,
    SharedInterestsResource
)
from friends.api.resources import (
    ConnectionsResource,
    ConnectionsSearchResource,
    FriendsNewCounterResource,
    FriendsNewResource,
    FriendsResource,
    MutualFriendsCountResource,
    NeoFriendsNewCounterResource,
    NeoFriendsNewResource,
    NeoFriendsResource
)
from goals.api.resources import (
    FacebookLikeResource,
    FacebookMutualLikeResource,
    FacebookOtherLikeResource,
    GoalResource,
    MatchFilterStateResource,
    OfferResource,
    SubjectResource
)
from interests.api.resources import (
    InterestResource,
    InterestSubjectResource,
    PoliticalIndexResource,
    PoliticalViewResource,
    ReligiousIndexResource,
    ReligiousViewResource
)
from matchfeed.api.resources import (
    MatchedFeedResource,
    MutualConnections,
    MutualFriendsResource,
    ProfileResource
)
from msgs.api.resources import (
    ChatMessageResource,
    InboxLastResource,
    InboxResource,
    MessageResource,
    UnreadMessageCounter
)
from photos.api.resources import (
    FacebookPhotoResource,
    OnBoardingFlowResource,
    UserResource
)
from world.api.resources import UserLocationResource

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(SubjectResource())
v1_api.register(UserResource())
v1_api.register(AboutMeResource())
v1_api.register(MatchFilterStateResource())
v1_api.register(FacebookPhotoResource())
v1_api.register(GoalResource())
v1_api.register(OfferResource())
v1_api.register(MatchedFeedResource())
v1_api.register(MutualFriendsResource())
v1_api.register(ProfileResource())
v1_api.register(MessageResource())
v1_api.register(InterestResource())
v1_api.register(InterestSubjectResource())
v1_api.register(FriendsResource())
v1_api.register(ConnectionsSearchResource())
v1_api.register(ConnectionsResource())
v1_api.register(FacebookLikeResource())
v1_api.register(FacebookMutualLikeResource())
v1_api.register(FacebookOtherLikeResource())
v1_api.register(InboxResource())
v1_api.register(InboxLastResource())
v1_api.register(UnreadMessageCounter())
v1_api.register(UserLocationResource())
v1_api.register(FriendsNewResource())
v1_api.register(FriendsNewCounterResource())
v1_api.register(EventResource())
v1_api.register(MembershipResource())
v1_api.register(FilterStateResource())
v1_api.register(EventFeedResource())
v1_api.register(EventConnections())
v1_api.register(EventAttendees())
v1_api.register(ChatMessageResource())
v1_api.register(OnBoardingFlowResource())
v1_api.register(ReligiousViewResource())
v1_api.register(ReligiousIndexResource())
v1_api.register(PoliticalViewResource())
v1_api.register(PoliticalIndexResource())
v1_api.register(UserProfileResource())

v2_api = Api(api_name='v2')
v2_api.register(NeoFriendsResource())
v2_api.register(NeoFriendsNewCounterResource())
v2_api.register(NeoFriendsNewResource())
v2_api.register(Attendees())
v2_api.register(MutualConnections())
v2_api.register(MutualFriendsCountResource())
v2_api.register(SocialLoginResource())
v2_api.register(TwitterSocialConnectResource())
v2_api.register(TwitterSocialDisconnectResource())
v2_api.register(LinkedinSocialConnectResource())
v2_api.register(LinkedinSocialDisconnectResource())
v2_api.register(OrganizerResource())
v2_api.register(SharedInterestsResource())


urlpatterns = patterns('',
                       url(r'^signup/interests', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/goals', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/offers', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/connect', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^signup/$', 'goals.views.signup_page',
                           name='onboardingflow'),
                       url(r'^api/', include(v1_api.urls)),
                       url(r'^api/', include(v2_api.urls)),
                       url(r'^facebook/', include('django_facebook.urls')),
                       url(r'^social/', include('social_auth.urls')),
                       url(r'^goals/close_login_popup/$', 'goals.views.close_login_popup', name='close_login_popup'),
                       url(r'^goals/error_window/$', 'goals.views.error_window', name='error_window'),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
                       url(r'^login/$', 'django.contrib.auth.views.login',
                           {'template_name': 'registration/login_dev.html'}, name='auth_login_dev'),
                       url(r'^accounts/', include('django_facebook.auth_urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       )


urlpatterns += patterns('',
                        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.MEDIA_ROOT}))

urlpatterns += patterns('',
                        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.STATIC_ROOT}))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            url(r'api/doc/', include('tastypie_swagger.urls', namespace='tastypie_swagger'))
                            )


urlpatterns += patterns('',
                        url(r'^.*$', 'goals.views.main_app')
                        )

bekindred/photos/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from .views import PhotoListView, PhotoDeleteView, CreateFacebookPhoto, photo_list

urlpatterns = patterns('',
                       url(r'^main/$', TemplateView.as_view(template_name="photos/main_photos.html")),
                       url(r'^create/$', photo_list, name='photo_list'),
                       url(r'^list/$', PhotoListView.as_view(), name='photo_create'),
                       url(r'^delete/(?P<pk>\d+)$', PhotoDeleteView.as_view(), name='photo_delete'),
                       url(r'^facebook/create$', CreateFacebookPhoto.as_view()),
                       )

bekindred/photos/models.py
import json

import time

import math
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_facebook.connect import _update_image
from django_facebook.models import FacebookCustomUser, PROFILE_IMAGE_PATH
from easy_thumbnails.fields import ThumbnailerImageField

from photos.utils import crop_photo


class Photo(models.Model):
    photo = models.FileField(upload_to='documents/%Y/%m/%d')
    user = models.ForeignKey(FacebookCustomUser)
    order = models.IntegerField(null=True)
    cropped_photo = models.TextField(default='')


class FacebookPhotoManager(models.Manager):
    @staticmethod
    def profile_photo(user_id):
        try:
            cropped_photo = FacebookPhoto.objects.filter(
                user=user_id, order=0)[0].cropped_photo
            if cropped_photo:
                return cropped_photo.url
        except IndexError:
            pass


class FacebookPhoto(models.Model):
    user = models.ForeignKey(FacebookCustomUser)
    photo = models.CharField(max_length=250)
    order = models.IntegerField(null=True)
    bounds = models.TextField(null=True)
    cropped_photo = ThumbnailerImageField(blank=True, null=True,
                                          upload_to=PROFILE_IMAGE_PATH,
                                          max_length=255)
    objects = FacebookPhotoManager()

    def clean(self):
        try:
            self.bounds = json.dumps(self.bounds)
        except ValueError:
            raise ValidationError(_(
                'Facebook photo bounds must be in json format')
            )

    def save(self, *args, **kwargs):
        if self.pk is None and self.photo and self.photo.startswith('http'):
            compose_image_name = '%s_%s' % (self.user.facebook_id,
                                            int(math.floor(time.time())))
            image_name, image_file = _update_image(compose_image_name,
                                                   self.photo)
            if not isinstance(self.bounds, dict):
                try:
                    cleared_bounds = self.bounds.replace("\'",
                                                         '"') if self.bounds else None
                    bounds = json.loads(cleared_bounds)
                except (ValueError, TypeError):
                    bounds = None
            else:
                bounds = self.bounds

            if bounds:
                filename, content = crop_photo(compose_image_name,
                                               image_file, bounds)
            else:
                filename, content = image_name, image_file
            self.cropped_photo = content
        super(FacebookPhoto, self).save(*args, **kwargs)

bekindred/photos/forms.py
from django import forms
from interests.models import Interest
from photos.models import Photo, FacebookPhoto


class PhotoForm(forms.Form):
    photo = forms.FileField()

    def __init__(self, user, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super(PhotoForm, self).clean()
        photo_count = Photo.objects.filter(user=self.user).count()
        if photo_count == 5:
            raise forms.ValidationError("Users can upload a max of 5 interests")
        return cleaned_data


class FacebookPhotoCreateForm(forms.ModelForm):
    class Meta:
        model = FacebookPhoto
        fields = ('photo',)

    def __init__(self, user, *args, **kwargs):
        super(FacebookPhotoCreateForm, self).__init__(*args, **kwargs)
        self.user = user

bekindred/photos/views.py
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Max
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, render
from django.template import RequestContext
from django.views.generic import DeleteView, CreateView, ListView
from open_facebook import OpenFacebook
from members.models import FacebookCustomUserActive
from .models import Photo, FacebookPhoto
from .forms import PhotoForm, FacebookPhotoCreateForm


def photo_list(request):
    # Handle file upload
    if request.method == 'POST':
        form = PhotoForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            order = 0
            max_order = Photo.objects.filter(user=request.user).aggregate(Max("order"))['order__max']

            if max_order:
                order = max_order + 1

            newdoc = Photo(photo=request.FILES['photo'], user=request.user, order=order)
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse_lazy('photo_list'))
    else:
        # A empty, unbound form
        form = PhotoForm(user=request.user)

    # Load documents for the list page
    documents = Photo.objects.filter(user=request.user)
    user = FacebookCustomUserActive.objects.get(pk=request.user.id)
    facebook_photos = FacebookPhoto.objects.filter(user_id=request.user)
    result_list = []
    for doc in documents:
        result_list.append(doc)

    for photo in facebook_photos:
        result_list.append(photo)

    # Render list page with the documents and the form
    return render_to_response(
        'photos/upload_photo.html',
        {'documents': result_list,
         'user': user,
         'form': form},
        context_instance=RequestContext(request)
    )


class PhotoListView(ListView):
    model = Photo
    template_name = 'photos/list.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class PhotoDeleteView(DeleteView):
    model = Photo
    template_name = 'photos/confirm_delete_photo.html'
    success_url = '/goals/'

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(PhotoDeleteView, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj


class CreateFacebookPhoto(CreateView):
    model = FacebookPhoto
    template_name = 'photos/create_photo_form.html'
    form_class = FacebookPhotoCreateForm
    fields = ['photo']
    success_url = '/photo/create/'

    def get_form_kwargs(self):
        kwargs = super(CreateFacebookPhoto, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user

        order = 0
        max_order = FacebookPhoto.objects.filter(user_id=self.request.user).aggregate(Max("order"))['order__max']
        if max_order:
            order = max_order + 1

        form.instance.order = order
        return super(CreateFacebookPhoto, self).form_valid(form)

    def get_context_data(self, **kwargs):
        fb_user = FacebookCustomUserActive.objects.get(id=self.request.user.id)
        if fb_user.facebook_id and fb_user.access_token:
            facebook = OpenFacebook(fb_user.access_token)
            data = facebook.get('me/photos/uploaded', fields='picture')['data']
        else:
            data = {}
        kwargs['facebook_photos'] = data
        return super(CreateFacebookPhoto, self).get_context_data(**kwargs)

bekindred/templates/photos/confirm_delete_photo.html
{% extends 'base.html' %}
{% block content %}
<section class="subtitle-wrapper">
    <div class="row">
        <div class="medium-10 small-centered columns">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-remove fa-stack-1x fa-inverse"></i>
            </span>
            <h5>Delete Photo?</h5>
        </div>
    </div>
</section>
<section class="edit-wrapper">
    <div class="row">
        <div class="columns small-centered small-12 medium-6 large-4">
            <form class="" action="" method="post">{% csrf_token %}
                <div data-alert class="alert-box alert">
                    Are you sure you want to delete <strong>"{{ object.description }}"</strong>?
                    <a href="" class="close">×</a>
                </div>
                <br>
                <a class="button delete success radius" href="/goals">Cancel</a>
                <button type="submit" class="danger submit-button radius">Delete</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

bekindred/templates/photos/create_photo_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container col-md-2 col-md-offset-5">
    <form action="" method="post">{% csrf_token %}
        {% if facebook_photos %}
            <ul>
                {% for photo in facebook_photos %}
                    <li><img width="100" src="{{ photo.picture }}"/>
                        <input id="id_photo" type="checkbox" name="photo" value="{{ photo.picture }}">
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No photos.</p>
        {% endif %}
        <input class="btn btn-default" type="submit" value="Create" />
    </form>
    </div>
{% endblock %}

bekindred/templates/photos/index.html
{% extends 'base.html' %}

{% block content %}
    {% if facebook_photos %}
        <ul>
            {% for photo in facebook_photos %}
                <li><img width="100" src="{{ photo.picture }}"/>
                    <input type="checkbox" name="photo_url" value="{{ photo.picture }}">
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No photos.</p>
    {% endif %}
{% endblock %}

bekindred/templates/photos/list.html
{% extends 'base.html' %}

{% block content %}
{% if object_list %}
    <ul>
        {% for photo in object_list %}
            <li><a href="{{ photo.photo.url }}">{{ photo.photo.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No documents.</p>
{% endif %}
{% endblock %}

bekindred/templates/photos/main_photos.html
{% extends 'base.html' %}
{% block content %}
    <div class="container col-md-3 col-md-offset-5">
    <div class="single-item">
        <div><h3>1</h3></div>
        <div><h3>2</h3></div>
        <div><h3>3</h3></div>
        <div><h3>4</h3></div>
        <div><h3>5</h3></div>
        <div><h3>6</h3></div>
    </div>
</div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.single-item').slick({

            });
        });
    </script>
{% endblock %}

bekindred/templates/photos/upload_photo.html
{% extends 'base.html' %}
<!-- List of uploaded documents -->
{% block content %}
<div class="container col-md-2 col-md-offset-5">
    <div class="single-item">
        <div><div class="image">
            <img src="http://graph.facebook.com/{{ user.profile_or_self.facebook_id }}/picture?type=large" width="200">
        </div></div>
        {% if documents %}
        {% for document in documents %}
        {% if document.photo.url %}
        <div><div class="image">
            <a href="{% url 'photo_delete' document.id %}"><span class="glyphicon glyphicon-minus-sign"></span>
                <img src="{{ document.photo.url }}" width="200">
            </a>
        </div></div>
        {% else %}
        <div><div class="image">
            <img src="{{ document.photo }}" width="200">
        </div></div>
        {% endif %}
        {% endfor %}
        {% else %}
        <p>No documents.</p>
        {% endif %}
    </div>
    <!-- Upload form. Note enctype attribute! -->
    <form action="{% url "photo_list" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <p>
            {{ form.photo.errors }}
            <input id="id_photo" type="file" name="photo" title="Add photo">
        </p>
    </br>
    <p><input class="btn btn-default" type="submit" value="Upload" /></p>
</br>
<p><a href="/photo/facebook/create" class="btn btn-default">Upload from Facebook</a></p>
</form>
</div>

{% endblock %}

{% block customscripts %}

<script type="text/javascript">
    $(document).ready(function(){
        // $('.single-item').slick({

        // });
        // $('input[type=file]').bootstrapFileInput();
    });
</script>
{% endblock %}